config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get 'posts/filter/:name' => 'posts#filter', as: :filtered_posts
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  validates :author, :title, :body, presence: true
  validates :tags, length: { minimum: 1, message: 'must have at least one tag' }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, presence: true
  validates :name, uniqueness: true

  def to_param
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc)
    # @tags = Tag.joins(:posts).group("posts_tags.tag_id").order("COUNT(tags.id) DESC")
    # @tags = Tag.all
    @tags = Tag.joins(:posts).select('tags.*, count(tag_id) as "tag_count"').group('tags.id').order('tag_count desc')
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def filter
    tag = Tag.find_by_name(params[:name])
    @posts = Post.joins(:posts_tags).where(posts_tags: { tag_id: tag.id }).order(updated_at: :desc)
    # @tags = Tag.joins(:posts_tags).select('tag_id, count(tag_id) as "tag_count"').group(:tag_id).order(' tag_count desc')
    # @tags = Tag.joins(:posts).group("posts_tags.tag_id").order("COUNT(tags.id) DESC")
    @tags = Tag.joins(:posts).select('tags.*, count(tag_id) as "tag_count"').group('tags.id').order('tag_count desc')
    # @tags = Tag.all
    render :index
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    tag_names = params['post']['tags_string'].gsub(',', ' ').split(' ')
    tag_names.each do |tag_name|
      tag = Tag.find_by_name(tag_name)
      tag = Tag.create(name: tag_name) unless tag
      @post.tags.push tag
    end

    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    @post.tags.clear
    tag_names = params['post']['tags_string'].gsub(',', ' ').split(' ')
    tag_names.each do |tag_name|
      tag = Tag.find_by_name(tag_name)
      tag = Tag.create(name: tag_name) unless tag
      @post.tags.push tag
    end

    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params['id'])
    post.destroy if post
    delete_free_tags
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:author, :title, :body)
  end

  def delete_free_tags
    Tag.all.each do |tag|
      tag.destroy if tag.posts.empty?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title SimpleRailsHw
    =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags

  body
    =yield

app/views/posts/_form.html.slim
-if @post.errors.any?
  - @post.errors.full_messages.each do |msg|
    p.error =msg

=form_for @post do |f|
  =f.label(:author, 'Author: ')
  br
  =f.text_field(:author, id: 'post_author')
  br
  =f.label(:title, 'Title: ')
  br
  =f.text_field(:title, id: 'post_title')
  br
  =f.label(:body, 'Body: ')
  br
  =f.text_area(:body, id: 'post_body')
  br
  =f.label(:tags_string, 'Tag field: ')
  br
  =f.text_field(:tags_string, value: (@post.tags.map { |e| e.name }).join(' '), id: 'post_tags_string')
  br
  =f.submit('Save')
  br
  =link_to 'Cancel', root_path

app/views/posts/edit.html.slim
h1 Edit post
= render :partial => 'form'

app/views/posts/index.html.slim
.posts
  center
    h1
      =link_to 'Posts', root_path
    hr

    b Filter by tag
    .tags
      - @tags.each do |tag|
        =link_to tag.name, filtered_posts_path(tag), class: 'filter-by-tag'
    hr

  =link_to 'New Post', new_post_path, class: 'button'
  br

  table
    - @posts.each do |post|
      tr.bottom-line id="post-row-#{post.id.to_s}"
        td width=150 valign='top'
          div
            h3.post-author =post.author
            div
              span.post-tags
                =(post.tags.map { |e| e.name }).join(', ')
        td valign='top'
          h4.post-title =post.title
          hr.dotted-line
          p.post-body =post.body
        td =link_to 'Edit', edit_post_path(post), class: 'edit_button'
        td =link_to 'Delete', post_path(post), method: :delete, class: 'destroy_button'

app/views/posts/new.html.slim
h1 New post
= render :partial => 'form'